### Recuperar totes les pel·lícules
GET http://localhost:1234/movies


### Resuprar generes
GET http://localhost:1234/genres

### Recuperar pel·lícula per id
GET http://localhost:1234/movies/9c6adabc-527f-11f0-bcd6-d843ae8f018a


### Recuperar pel·lícules per genere
GET http://localhost:1234/movies?genre=crime

### Crea una pel·lícula

POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Eliminar una pel·lícula
DELETE http://localhost:1234/movies/042beb5c-54e9-11f0-8445-d843ae8f018a

### Actualitzar un pel·lícula

PATCH http://localhost:1234/movies/9e87e5ab-54e9-11f0-8445-d843ae8f018a
Content-Type: application/json

{
    "year": 1993
}

